# # Setup fzf
# # ---------
# if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
#   PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
# fi

# # Auto-completion
# # ---------------
# [[ $- == *i* ]] && source "/opt/homebrew/opt/fzf/shell/completion.zsh" 2> /dev/null

# # Key bindings
# # ------------
# source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"


# ---------------
# Above is generated by brew

# Auto-completion
# ---------------
source ~/.fzf/completion.zsh

# Key bindings
# ------------
source ~/.fzf/key-bindings.zsh

export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --info=inline'
export FZF_CTRL_R_OPTS='--no-sort' # default sort by: relevance -> chronological
